### ISSUE TITLE
Addon does not work if Vue component is partially initialized

### ISSUE THREAD

**Issue by krlmari** [Sidnioulz/storybook-addon-vue-mdx#11]
### Context
For some reason I'm getting an error when creating .mdx containing a "partially initialized" component. Partially initialized means that one of three optional properties was not set in component: `template`, `script`, `style`. For my case it was `style` property (it also requires to have at least one declared style!)

### Steps to reproduce:
1. Create a component without `style` property (B.vue):
```vue
<script setup>
import A from "@src/components/A/A.vue";
</script>

<template>
  <h1 style="margin: 20px">Hello</h1>
  <A />
</template>
```
2. Create an `.mdx` file rendering this component:
```vue
import B from "../../dev/B.vue";
import { Meta, Story } from "@storybook/blocks";

<Meta title="B" component={B} />; # B
<B></B>
```
3. Open storybook and see this error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `MDXContent`.
```

### Steps to fix:
1. Add style property (at least 1 css property should be declared, have no clue why):
```vue
<script setup>
import A from "@src/components/A/A.vue";
</script>

<template>
  <h1 style="margin: 20px">Hello</h1>
  <A />
</template>

<style scoped>
asdf {}
</style>
```
2. Same as step 2 from reproducing guide
3. Open storybook and it works!

**Comment by Sidnioulz** [comment]
Hi!

Thanks for your report. We have used this addon with components that didn't have a style tag, so I'm not sure if this is a regression or if there's another necessary condition to trigger the bug.

Are you able to reproduce the bug in a new stack, e.g. one made with https://storybook.new? Or only on your own repo?

Thanks

**Comment by krlmari** [comment]
Here's the reproducible repo: https://github.com/krlmari/test-storybook-addon-vue-mdx

**Comment by Sidnioulz** [comment]
Thanks!

The bug was in the heuristic that distinguishes React vs Vue components. If you have other cases that bug out, please send them my way! I need more diverse styles of Vue components to correctly detect them in the MDX tree and process them through Vue.

Version 1.0.5 should be out in a few minutes with the bug fix for this one.
