### ISSUE TITLE
Contribution rights request

### ISSUE THREAD

**Issue by Romainpetit** [Sidnioulz/storybook-addon-vue-mdx#4]
Hello dear @Sidnioulz, 
I would like to propose a PR to make the addon compatible with Storybook 8. 

While the repo welcomes contributions, the current access rights don't seem to allow branch creation: 
![Screenshot 2024-07-16 at 16 59 51](https://github.com/user-attachments/assets/672f4b53-8f51-4b1a-a770-0f84917e692c)

Could you look into it, please?
Thanks ❤️

**Comment by Sidnioulz** [comment]
Hey there! :)

I invited you to the repo. Check your email! Thanks for contributing. I thought it was running but I haven't tested it properly.

The usual workflow for GitHub FOSS projects is you fork, commit your changes, and when you open a PR, it lets you select the origin repo as a target and then opens the PR on my side for me to review. This way, you don't need permissions.
